// STREHË system-map bootstrap (curated from read-only inspection, verified against
// the repository by the baseline Worker). This is the Coordinator's INITIAL
// understanding; future change-aware reviews refine it. Not a framework.

export const MODULES = [
  {
    name: "Marketing site", category: "web", criticality: "high",
    purpose: "Public marketing pages, SEO, legal content, company profile, locale routing.",
    source_paths: ["app/[locale]", "app/(marketing)", "lib/marketing", "proxy.ts", "app/robots.ts", "app/sitemap.ts"],
    external: ["Vercel"],
    notes: "Apex→www routing + x-strehe-surface/x-strehe-locale headers live in proxy.ts.",
  },
  {
    name: "Auth / RBAC", category: "security", criticality: "high",
    purpose: "Login, callback, role gating, worker access, app-user identity.",
    source_paths: ["lib/auth", "app/auth", "app/unauthorized"],
    db_deps: ["app_users"],
    notes: "Roles: admin/office/field/contractor/household. is_active_*() helpers gate RLS.",
  },
  {
    name: "CRM / Leads", category: "crm", criticality: "high",
    purpose: "Lead records, interactions, audit events, follow-ups, attribution.",
    source_paths: ["lib/actions/leads.ts", "app/leads", "lib/funnel/attribution.ts"],
    db_deps: ["leads", "lead_interactions", "lead_events"],
    notes: "lead_events is the audit log (event_type + summary + metadata jsonb).",
  },
  {
    name: "Clients", category: "crm", criticality: "high",
    purpose: "Converted-customer records (individual/business).",
    source_paths: ["app/clients"],
    db_deps: ["clients"],
  },
  {
    name: "Properties", category: "ops", criticality: "high",
    purpose: "Managed properties, addresses, contacts, keys.",
    source_paths: ["app/properties"],
    db_deps: ["properties", "locations", "municipalities"],
  },
  {
    name: "Services / Packages", category: "ops", criticality: "medium",
    purpose: "Service catalog and package definitions.",
    source_paths: ["app/services", "app/packages", "lib/funnel/package-map.ts"],
    db_deps: ["services", "packages", "package_services"],
  },
  {
    name: "Subscriptions", category: "ops", criticality: "high",
    purpose: "Recurring service contracts per client/property/package.",
    source_paths: ["app/subscriptions"],
    db_deps: ["subscriptions", "subscription_tasks"],
  },
  {
    name: "Tasks / Workers", category: "ops", criticality: "medium",
    purpose: "Operational tasks, worker roster, scheduled task generation.",
    source_paths: ["app/tasks", "app/workers", "lib/actions/task-generator.ts", "lib/actions/workers.ts", "app/api/cron/generate-tasks"],
    db_deps: ["tasks", "workers", "task_templates", "task_attachments", "task_reports", "worker_role_title_history"],
    notes: "generate-tasks is deterministic (subscription→due-date), run by Vercel cron Sun 08:00.",
  },
  {
    name: "Billing / Invoicing", category: "finance", criticality: "high",
    purpose: "Invoices, payments, credit notes, settlement, PDF generation.",
    source_paths: ["app/billing", "lib/billing", "lib/actions/billing.ts"],
    db_deps: ["invoices", "invoice_items", "payments", "credit_note_number_sequences", "invoice_number_sequences"],
    notes: "Payments are append-only; invoice authorization via RLS policy.",
  },
  {
    name: "Banking", category: "finance", criticality: "medium",
    purpose: "Banks, company accounts, bank-identifier detection.",
    source_paths: ["app/settings/banking", "lib/banking"],
    db_deps: ["banks", "company_bank_accounts", "bank_identifiers"],
  },
  {
    name: "Expenses", category: "finance", criticality: "medium",
    purpose: "Expense tracking + categories.",
    source_paths: ["app/expenses", "lib/actions/expenses.ts", "lib/actions/expense-categories.ts"],
    db_deps: ["expenses", "expense_categories"],
  },
  {
    name: "Finance overview", category: "finance", criticality: "low",
    purpose: "Aggregate finance dashboard.",
    source_paths: ["app/finance", "lib/finance"],
  },
  {
    name: "Messaging ingestion", category: "messaging", criticality: "high",
    purpose: "Meta webhook verify+journal, ingestion queue, normalization, identity resolution, conversation/message persistence.",
    source_paths: ["lib/meta", "lib/messaging/ingest.ts", "lib/messaging/parser.ts", "lib/messaging/normalize.ts", "lib/messaging/resolution.ts", "app/api/meta/webhook", "app/api/cron/meta-ingest"],
    db_deps: ["meta_webhook_events", "meta_ingestion_queue", "contact_channel_identities", "conversations", "conversation_messages"],
    external: ["Meta (WhatsApp/Instagram/Messenger)"],
    notes: "HMAC-SHA256 union-of-secrets verify; claim_meta_ingestion_batch (SKIP LOCKED).",
  },
  {
    name: "Operator Inbox", category: "messaging", criticality: "high",
    purpose: "Human conversation triage: state, assignment, identity link, reply.",
    source_paths: ["app/operator/inbox", "lib/actions/inbox.ts"],
    db_deps: ["conversations", "conversation_messages", "contact_channel_identities"],
    notes: "admin/office only; can_manage_messaging() excludes agent principals.",
  },
  {
    name: "Outbound messaging", category: "messaging", criticality: "high",
    purpose: "Human-authorized send via Meta Graph API (WhatsApp/Instagram/Messenger).",
    source_paths: ["lib/messaging/send"],
    external: ["Meta Graph API"],
    notes: "sendReply in inbox.ts is the only send path; agents have no send capability.",
  },
  {
    name: "Notification / Email", category: "messaging", criticality: "medium",
    purpose: "Inbox notification queue + email alerts; inquiry/promotion emails.",
    source_paths: ["lib/messaging/notify.ts", "lib/email", "lib/server/meta-ingest-handler.ts"],
    db_deps: ["inbox_notification_queue"],
    external: ["Resend (email)"],
  },
  {
    name: "Funnel / Offers", category: "sales", criticality: "high",
    purpose: "Qualification→consultation→offer→contract→payment funnel; founding-customer capacity.",
    source_paths: ["lib/funnel", "lib/actions/funnel.ts", "app/leads/[id]/FunnelPanel.tsx"],
    db_deps: ["lead_consultations", "lead_offers", "founding_customer_capacity"],
  },
  {
    name: "Promotions", category: "sales", criticality: "medium",
    purpose: "Promotion codes + campaigns applied to billing.",
    source_paths: ["app/settings/promotions", "lib/promotions", "lib/actions/promotions.ts"],
    db_deps: ["promotion_codes", "promotion_campaigns", "promotion_redemptions"],
  },
  {
    name: "Keys / Key logs", category: "ops", criticality: "low",
    purpose: "Property keys and key-handover logs.",
    source_paths: ["app/keys", "lib/key-log.ts", "lib/key-status.ts"],
    db_deps: ["keys", "key_logs"],
  },
  {
    name: "Agent framework (DB substrate)", category: "runtime", criticality: "medium",
    purpose: "Dormant review-gated agent job queue (principals/capabilities/jobs/runs/artifacts).",
    source_paths: ["supabase/migrations/20260611120000_add_household_and_agent_foundations.sql", "supabase/migrations/20260612110000_harden_agent_identity_boundary.sql"],
    db_deps: ["agent_principals", "agent_capabilities", "agent_jobs", "agent_runs", "agent_artifacts", "household_spaces", "household_members", "household_projects"],
    notes: "No production code drives it; GMK worker is the first consumer.",
  },
  {
    name: "GMK Agent Worker", category: "runtime", criticality: "medium",
    purpose: "Local Engineering agent runtime (claim loop, tool gateway, Coordinator/Worker, SQLite memory).",
    source_paths: ["scripts/gmk-agent-worker"],
    external: ["Ollama (loopback, CPU-only)"],
    notes: "Phase 1 committed at 4624e54.",
  },
  {
    name: "Inspection Lab (photo comparison)", category: "post-v1", criticality: "deferred",
    purpose: "Room-photo baseline/current comparison with local+cloud vision. OUT OF SCOPE V1.",
    source_paths: ["app/inspection-lab", "lib/inspection-lab"],
    db_deps: ["inspection_lab_cases", "inspection_lab_case_photos", "inspection_lab_tracked_objects", "inspection_lab_object_markers"],
    notes: "DEFERRED (mapped for boundary only).",
  },
  {
    name: "Finance Agent (local Python)", category: "post-v1", criticality: "deferred",
    purpose: "Separate local Python finance project. OUT OF SCOPE V1.",
    source_paths: ["../strehe-finance-local"],
    notes: "DEFERRED (separate repo/project, reference only).",
  },
  {
    name: "Supabase infra", category: "infra", criticality: "high",
    purpose: "Migrations, RLS, RPCs, seed, config.",
    source_paths: ["supabase/migrations", "supabase/config.toml", "supabase/seed.sql", "supabase/tests"],
    notes: "~80 migrations; messaging ingestion + agent framework + billing RPCs all defined here.",
  },
];

// Ordered end-to-end processes (behavioral map). Steps are module-level.
export const FLOWS = [
  {
    name: "Messaging (inbound→outbound)",
    steps: [
      "Meta inbound message",
      "webhook HMAC verification (lib/meta/verify.ts)",
      "webhook journal (meta_webhook_events)",
      "ingestion queue enqueue (trigger)",
      "claim_meta_ingestion_batch (worker)",
      "normalize/parse (lib/messaging/parser.ts)",
      "identity resolution (resolve_contact_identity_whatsapp)",
      "conversation/message persist (ingest_conversation_message)",
      "attention/unread state (needs_reply)",
      "inbox notification (enqueue_inbox_notification)",
      "Operator Inbox (human triage)",
      "human outbound reply (sendReply → Meta Graph API)",
    ],
    entry: ["app/api/meta/webhook/route.ts"],
    evidence: ["lib/meta/create-handlers.ts", "lib/messaging/ingest.ts", "lib/actions/inbox.ts", "lib/messaging/send/index.ts"],
  },
  {
    name: "Commercial / customer lifecycle",
    steps: [
      "inquiry (website form / Meta / manual)",
      "lead creation + attribution (createLeadAction)",
      "qualification (leads.status/lifecycle)",
      "consultation (lead_consultations)",
      "offer (lead_offers, founding-customer capacity)",
      "contract → client/property/subscription",
      "payment/activation (payments, billing)",
    ],
    entry: ["lib/security/public-contact.ts", "lib/actions/leads.ts"],
    evidence: ["lib/funnel/transitions.ts", "lib/actions/funnel.ts", "lib/billing/settlement.ts", "app/subscriptions"],
    note: "Exact chain verified against lib/funnel + app/subscriptions; not assumed.",
  },
  {
    name: "Auth / RBAC",
    steps: [
      "login (email/username+password)",
      "callback (exchange code → session)",
      "role resolution (app_users.role)",
      "route gating (requireRole)",
      "RLS (is_active_app_user/is_active_business_user/is_app_admin)",
    ],
    entry: ["app/auth/login/page.tsx", "app/auth/callback/route.ts"],
    evidence: ["lib/auth/require-role.ts", "lib/auth/roles.ts"],
  },
  {
    name: "Scheduled task generation",
    steps: [
      "Vercel cron (Sun 08:00)",
      "generate-tasks handler (CRON_SECRET bearer)",
      "deterministic due-date computation (task-generator.ts)",
      "task insert (idempotent by subscription+service+due_date)",
    ],
    entry: ["app/api/cron/generate-tasks/route.ts"],
    evidence: ["lib/server/generate-tasks-handler.ts", "lib/actions/task-generator.ts"],
  },
  {
    name: "Agent job lifecycle (GMK)",
    steps: [
      "job enqueue (agent_jobs, required_capability)",
      "discovery (eligible jobs SELECT)",
      "claim_agent_job (lease)",
      "renew_agent_job_lease (long jobs)",
      "worker execution (tools + ollama)",
      "output validation (privacy/forbidden/secrets)",
      "complete_agent_job → awaiting_review / fail_agent_job",
      "review_agent_job (human, post-hoc)",
    ],
    entry: ["scripts/gmk-agent-worker/worker.mjs"],
    evidence: ["scripts/gmk-agent-worker/lib/claim-loop.mjs", "supabase/migrations/20260611120000_add_household_and_agent_foundations.sql"],
  },
];

// Module-level dependency edges (for change-impact analysis), not file-to-file noise.
export const DEPENDENCIES = [
  ["Auth / RBAC", "CRM / Leads"],
  ["Auth / RBAC", "Operator Inbox"],
  ["Auth / RBAC", "Billing / Invoicing"],
  ["Auth / RBAC", "GMK Agent Worker"],
  ["Messaging ingestion", "Operator Inbox"],
  ["Messaging ingestion", "Notification / Email"],
  ["Operator Inbox", "Outbound messaging"],
  ["Outbound messaging", "Notification / Email"],
  ["CRM / Leads", "Funnel / Offers"],
  ["CRM / Leads", "Messaging ingestion"],
  ["Funnel / Offers", "Subscriptions"],
  ["Subscriptions", "Tasks / Workers"],
  ["Subscriptions", "Billing / Invoicing"],
  ["Clients", "Subscriptions"],
  ["Properties", "Subscriptions"],
  ["Services / Packages", "Subscriptions"],
  ["Billing / Invoicing", "Banking"],
  ["Billing / Invoicing", "Promotions"],
  ["Agent framework (DB substrate)", "GMK Agent Worker"],
  ["Supabase infra", "Messaging ingestion"],
  ["Supabase infra", "Agent framework (DB substrate)"],
];
