// STREHË system-map bootstrap (curated from read-only inspection, verified against
// the repository by the baseline Worker). This is the Coordinator's INITIAL
// understanding; future change-aware reviews refine it. Not a framework.

// Exact repository-wide/support paths that are intentionally not attributed to
// an application module. This list is audit policy, not a glob exemption.
export const KNOWN_GLOBAL_PATHS = Object.freeze([
  { path: ".gitignore", kind: "repository-support", reason: "Repository-wide ignore policy." },
  { path: "package.json", kind: "repository-support", reason: "Repository-wide scripts and dependencies." },
  { path: "playwright.entry-security.config.ts", kind: "test-support", reason: "Shared entry-security test configuration." },
  { path: "components/layout/AppShell.tsx", kind: "shared-ui", reason: "Cross-module application shell." },
  { path: "components/ui/StatusBadge.tsx", kind: "shared-ui", reason: "Cross-module status presentation primitive." },
  { path: "docs/architecture/ENGINEERING-AGENT-V1-SPEC.md", kind: "documentation", reason: "Engineering runtime architecture reference." },
  { path: "docs/operations/engineering-agent-proactive-operator-runbook.md", kind: "documentation", reason: "Engineering runtime operator runbook." },
  { path: "docs/operations/multi-agent-router-p0-p2-configuration.md", kind: "documentation", reason: "Engineering router configuration reference." },
  { path: "tests/fixtures/inbox/a-albanian-services.json", kind: "test-fixture", reason: "Inbox Agent deterministic fixture." },
  { path: "tests/fixtures/inbox/b-diaspora-property-check.json", kind: "test-fixture", reason: "Inbox Agent deterministic fixture." },
  { path: "tests/fixtures/inbox/c-moisture-mold.json", kind: "test-fixture", reason: "Inbox Agent deterministic fixture." },
  { path: "tests/fixtures/inbox/d-electrical-safety.json", kind: "test-fixture", reason: "Inbox Agent deterministic fixture." },
  { path: "tests/fixtures/inbox/e-unclear-request.json", kind: "test-fixture", reason: "Inbox Agent deterministic fixture." },
  { path: "tests/fixtures/inbox/f-price-contract.json", kind: "test-fixture", reason: "Inbox Agent deterministic fixture." },
  { path: "tests/fixtures/inbox/g-frustrated-customer.json", kind: "test-fixture", reason: "Inbox Agent deterministic fixture." },
  { path: "tests/fixtures/inbox/h-prompt-injection.json", kind: "test-fixture", reason: "Inbox Agent deterministic fixture." },
  { path: "tests/fixtures/inbox/i-send-immediately.json", kind: "test-fixture", reason: "Inbox Agent deterministic fixture." },
  { path: "tests/fixtures/inbox/j-social-instagram.json", kind: "test-fixture", reason: "Inbox Agent deterministic fixture." },
  { path: "tests/fixtures/inbox/k-english-inquiry.json", kind: "test-fixture", reason: "Inbox Agent deterministic fixture." },
]);

export const MODULES = [
  {
    name: "Marketing site", category: "web", criticality: "high",
    purpose: "Public marketing pages, SEO, legal content, company profile, locale routing.",
    source_paths: ["app/[locale]", "app/page.tsx", "app/privacy", "app/terms", "app/data-deletion", "lib/marketing", "proxy.ts", "app/robots.ts", "app/sitemap.ts", "scripts/capture-manual-screenshots.mjs"],
    external: ["Vercel"],
    tests: ["tests/e2e/public-website-smoke.spec.ts", "tests/unit/seo-discoverability.spec.ts"],
    notes: "Apex→www routing + x-strehe-surface/x-strehe-locale headers live in proxy.ts.",
  },
  {
    name: "Auth / RBAC", category: "security", criticality: "high",
    purpose: "Login, callback, role gating, worker access, app-user identity.",
    source_paths: ["lib/auth", "app/auth", "app/unauthorized", "app/users", "app/settings/users"],
    db_deps: ["app_users"],
    rpc_deps: ["is_active_app_user", "is_active_business_user", "is_app_admin", "is_active_agent", "is_household_member", "can_manage_messaging", "can_manage_billing", "can_manage_sales_funnel", "can_manage_household", "can_edit_household"],
    tests: ["tests/e2e/auth.setup.ts", "tests/unit/internal-path.spec.ts"],
    notes: "Roles: admin/office/field/contractor/household. is_active_*() helpers gate RLS.",
  },
  {
    name: "CRM / Leads", category: "crm", criticality: "high",
    purpose: "Lead records, interactions, audit events, follow-ups, attribution.",
    source_paths: ["lib/actions/leads.ts", "app/leads", "lib/funnel/attribution.ts"],
    db_deps: ["leads", "lead_interactions", "lead_events"],
    rpc_deps: ["protect_lead_first_touch"],
    tests: ["tests/e2e/leads-smoke.spec.ts", "tests/unit/public-contact.spec.ts"],
    notes: "lead_events is the audit log (event_type + summary + metadata jsonb).",
  },
  {
    name: "Clients", category: "crm", criticality: "high",
    purpose: "Converted-customer records (individual/business).",
    source_paths: ["app/clients"],
    db_deps: ["clients"],
  },
  {
    name: "Properties", category: "ops", criticality: "high",
    purpose: "Managed properties, addresses, contacts, keys.",
    source_paths: ["app/properties"],
    db_deps: ["properties", "locations", "municipalities"],
    tests: ["tests/e2e/properties-smoke.spec.ts"],
  },
  {
    name: "Services / Packages", category: "ops", criticality: "medium",
    purpose: "Service catalog and package definitions.",
    source_paths: ["app/services", "app/packages", "lib/funnel/package-map.ts"],
    db_deps: ["services", "packages", "package_services"],
  },
  {
    name: "Subscriptions", category: "ops", criticality: "high",
    purpose: "Recurring service contracts per client/property/package.",
    source_paths: ["app/subscriptions"],
    db_deps: ["subscriptions", "subscription_tasks"],
    tests: ["tests/e2e/contracts-smoke.spec.ts", "tests/e2e/subscription-generator.spec.ts", "tests/unit/activation.spec.ts"],
  },
  {
    name: "Tasks / Workers", category: "ops", criticality: "medium",
    purpose: "Operational tasks, worker roster, scheduled task generation.",
    source_paths: ["app/tasks", "app/workers", "lib/actions/task-generator.ts", "lib/actions/workers.ts", "app/api/cron/generate-tasks"],
    db_deps: ["tasks", "workers", "task_templates", "task_attachments", "task_reports", "worker_role_title_history"],
    tests: ["tests/e2e/operations-smoke.spec.ts", "tests/e2e/tasks-smoke.spec.ts", "tests/unit/cron-authorization.spec.ts"],
    notes: "generate-tasks is deterministic (subscription→due-date), run by Vercel cron Sun 08:00.",
  },
  {
    name: "Billing / Invoicing", category: "finance", criticality: "high",
    purpose: "Invoices, payments, credit notes, settlement, PDF generation.",
    source_paths: ["app/billing", "lib/billing", "lib/actions/billing.ts"],
    db_deps: ["invoices", "invoice_items", "payments", "credit_note_number_sequences", "invoice_number_sequences"],
    rpc_deps: ["issue_billing_document_with_number", "next_billing_document_number", "forbid_payment_mutation", "protect_payment_idempotency_key"],
    tests: ["tests/unit/payment-idempotency.spec.ts"],
    notes: "Payments are append-only; invoice authorization via RLS policy.",
  },
  {
    name: "Banking", category: "finance", criticality: "medium",
    purpose: "Banks, company accounts, bank-identifier detection.",
    source_paths: ["app/settings/banking", "lib/banking"],
    db_deps: ["banks", "company_bank_accounts", "bank_identifiers"],
    tests: ["tests/e2e/banking-smoke.spec.ts"],
  },
  {
    name: "Expenses", category: "finance", criticality: "medium",
    purpose: "Expense tracking + categories.",
    source_paths: ["app/expenses", "lib/actions/expenses.ts", "lib/actions/expense-categories.ts"],
    db_deps: ["expenses", "expense_categories"],
  },
  {
    name: "Finance overview", category: "finance", criticality: "low",
    purpose: "Aggregate finance dashboard.",
    source_paths: ["app/finance", "lib/finance"],
    tests: ["tests/e2e/finance-smoke.spec.ts"],
  },
  {
    name: "Messaging ingestion", category: "messaging", criticality: "high",
    purpose: "Meta webhook verify+journal, ingestion queue, normalization, identity resolution, conversation/message persistence.",
    source_paths: ["lib/meta", "lib/messaging/ingest.ts", "lib/messaging/parser.ts", "lib/messaging/normalize.ts", "lib/messaging/resolution.ts", "app/api/meta/webhook", "app/api/cron/meta-ingest"],
    db_deps: ["meta_webhook_events", "meta_ingestion_queue", "contact_channel_identities", "conversations", "conversation_messages"],
    rpc_deps: ["claim_meta_ingestion_batch", "meta_ingestion_mark_completed", "meta_ingestion_mark_failure", "meta_webhook_events_enqueue", "ingest_conversation_message", "ensure_conversation", "resolve_contact_identity_whatsapp", "upsert_contact_channel_identity"],
    external: ["Meta (WhatsApp/Instagram/Messenger)"],
    tests: ["supabase/tests/messaging_ingestion.test.sql", "supabase/tests/messaging_privileges_production_check.sql", "tests/unit/messaging-ingest.spec.ts", "tests/unit/messaging-normalize.spec.ts", "tests/unit/messaging-parser.spec.ts", "tests/unit/meta-ingest-cron.spec.ts", "tests/unit/meta-webhook.spec.ts"],
    notes: "HMAC-SHA256 union-of-secrets verify; claim_meta_ingestion_batch (SKIP LOCKED).",
  },
  {
    name: "Operator Inbox", category: "messaging", criticality: "high",
    purpose: "Human conversation triage: state, assignment, identity link, reply.",
    source_paths: ["app/operator/inbox", "lib/actions/inbox.ts"],
    db_deps: ["conversations", "conversation_messages", "contact_channel_identities"],
    rpc_deps: ["operator_set_conversation_assignment", "operator_set_conversation_state", "operator_set_identity_resolution"],
    notes: "admin/office only; can_manage_messaging() excludes agent principals.",
  },
  {
    name: "Outbound messaging", category: "messaging", criticality: "high",
    purpose: "Human-authorized send via Meta Graph API (WhatsApp/Instagram/Messenger).",
    source_paths: ["lib/messaging/send"],
    rpc_deps: ["settle_outbound_message"],
    external: ["Meta Graph API"],
    notes: "sendReply in inbox.ts is the only send path; agents have no send capability.",
  },
  {
    name: "Notification / Email", category: "messaging", criticality: "medium",
    purpose: "Inbox notification queue + email alerts; inquiry/promotion emails.",
    source_paths: ["lib/messaging/notify.ts", "lib/email", "lib/server/meta-ingest-handler.ts"],
    db_deps: ["inbox_notification_queue"],
    rpc_deps: ["enqueue_inbox_notification", "claim_inbox_notification_batch", "inbox_notification_mark_sent", "inbox_notification_mark_failure"],
    external: ["Resend (email)"],
    tests: ["tests/unit/inbox-notification-email.spec.ts", "tests/unit/inquiry-notification-email.spec.ts"],
  },
  {
    name: "Funnel / Offers", category: "sales", criticality: "high",
    purpose: "Qualification→consultation→offer→contract→payment funnel; founding-customer capacity.",
    source_paths: ["lib/funnel", "lib/actions/funnel.ts", "app/leads/[id]/FunnelPanel.tsx", "scripts/verify-founding-funnel-local.mjs"],
    db_deps: ["lead_consultations", "lead_offers", "founding_customer_capacity"],
    rpc_deps: ["enforce_founding_customer_capacity", "enforce_offer_lifecycle"],
    tests: ["tests/unit/founding-funnel.spec.ts"],
  },
  {
    name: "Promotions", category: "sales", criticality: "medium",
    purpose: "Promotion codes + campaigns applied to billing.",
    source_paths: ["app/settings/promotions", "lib/promotions", "lib/actions/promotions.ts"],
    db_deps: ["promotion_codes", "promotion_campaigns", "promotion_redemptions"],
  },
  {
    name: "Keys / Key logs", category: "ops", criticality: "low",
    purpose: "Property keys and key-handover logs.",
    source_paths: ["app/keys", "lib/key-log.ts", "lib/key-status.ts"],
    db_deps: ["keys", "key_logs"],
    tests: ["tests/e2e/keys-smoke.spec.ts"],
  },
  {
    name: "Vendors", category: "finance", criticality: "low",
    purpose: "Supplier/service vendor records linked to expenses.",
    source_paths: ["app/settings/vendors", "lib/actions/vendors.ts"],
    db_deps: ["vendors"],
  },
  {
    name: "Agent framework (DB substrate)", category: "runtime", criticality: "medium",
    purpose: "Dormant review-gated agent job queue (principals/capabilities/jobs/runs/artifacts).",
    source_paths: ["supabase/migrations/20260611120000_add_household_and_agent_foundations.sql", "supabase/migrations/20260612110000_harden_agent_identity_boundary.sql"],
    db_deps: ["agent_principals", "agent_capabilities", "agent_jobs", "agent_runs", "agent_artifacts", "household_spaces", "household_members", "household_projects"],
    rpc_deps: ["claim_agent_job", "complete_agent_job", "fail_agent_job", "review_agent_job", "heartbeat_agent", "renew_agent_job_lease", "agent_has_capability", "is_agent_assigned_to_job", "can_read_agent_job", "can_read_agent_artifact", "enforce_separate_human_agent_identity"],
    notes: "No production code drives it; GMK worker is the first consumer.",
  },
  {
    name: "Agent operator controls", category: "runtime", criticality: "high",
    purpose: "Authenticated operator dashboard and bounded admin controls for Engineering Agent status, pause/resume, findings, and review submission.",
    source_paths: [
      "app/operator/agents",
      "lib/agents/operator-view.ts",
      "supabase/migrations/20260821120000_engineering_proactive_operator_controls.sql",
      "supabase/migrations/20260831120000_engineering_review_submission_hardening.sql",
    ],
    db_deps: ["agent_operator_controls", "agent_principals", "agent_capabilities", "agent_jobs"],
    rpc_deps: [
      "get_engineering_agent_dashboard",
      "operator_control_engineering_agent",
      "operator_update_engineering_finding_lifecycle",
      "operator_enqueue_engineering_review",
    ],
    tests: ["tests/unit/agent-operator.spec.ts", "supabase/tests/engineering_proactive_operator.test.sql"],
    notes: "Admin mutations re-authorize server-side; review requester provenance is always auth.uid().",
  },
  {
    name: "GMK Agent Worker", category: "runtime", criticality: "medium",
    purpose: "Local Engineering agent runtime (claim loop, tool gateway, Coordinator/Worker, SQLite memory).",
    source_paths: ["scripts/gmk-agent-worker"],
    external: ["Ollama (loopback, CPU-only)"],
    notes: "Phase 1 committed at 4624e54.",
  },
  {
    name: "Inspection Lab (photo comparison)", category: "post-v1", criticality: "deferred",
    purpose: "Room-photo baseline/current comparison with local+cloud vision. OUT OF SCOPE V1.",
    source_paths: ["app/inspection-lab", "lib/inspection-lab", "scripts/run-bathroom-base-shot-engine.mjs"],
    db_deps: ["inspection_lab_cases", "inspection_lab_case_photos", "inspection_lab_tracked_objects", "inspection_lab_object_markers"],
    tests: ["tests/unit/inspection-lab-access.spec.ts"],
    notes: "DEFERRED (mapped for boundary only).",
  },
  {
    name: "Finance Agent (local Python)", category: "post-v1", criticality: "deferred",
    purpose: "Separate local Python finance project. OUT OF SCOPE V1.",
    source_paths: ["../strehe-finance-local"],
    notes: "DEFERRED (separate repo/project, reference only).",
  },
  {
    name: "Supabase infra", category: "infra", criticality: "high",
    purpose: "Migrations, RLS, RPCs, seed, config.",
    source_paths: ["supabase/migrations", "supabase/config.toml", "supabase/seed.sql", "supabase/tests"],
    notes: "~59 migrations; messaging ingestion + agent framework + billing RPCs all defined here.",
  },
];

// Ordered end-to-end processes (behavioral map). Steps are module-level.
export const FLOWS = [
  {
    name: "Messaging (inbound→outbound)",
    steps: [
      "Meta inbound message",
      "webhook HMAC verification (lib/meta/verify.ts)",
      "webhook journal (meta_webhook_events)",
      "ingestion queue enqueue (trigger)",
      "claim_meta_ingestion_batch (worker)",
      "normalize/parse (lib/messaging/parser.ts)",
      "identity resolution (resolve_contact_identity_whatsapp)",
      "conversation/message persist (ingest_conversation_message)",
      "attention/unread state (needs_reply)",
      "inbox notification (enqueue_inbox_notification)",
      "Operator Inbox (human triage)",
      "human outbound reply (sendReply → Meta Graph API)",
    ],
    entry: ["app/api/meta/webhook/route.ts"],
    evidence: ["lib/meta/create-handlers.ts", "lib/messaging/ingest.ts", "lib/actions/inbox.ts", "lib/messaging/send/index.ts"],
  },
  {
    name: "Commercial / customer lifecycle",
    steps: [
      "inquiry (website form / Meta / manual)",
      "lead creation + attribution (createLeadAction)",
      "qualification (leads.status/lifecycle)",
      "consultation (lead_consultations)",
      "offer (lead_offers, founding-customer capacity)",
      "contract → client/property/subscription",
      "payment/activation (payments, billing)",
    ],
    entry: ["lib/security/public-contact.ts", "lib/actions/leads.ts"],
    evidence: ["lib/funnel/transitions.ts", "lib/actions/funnel.ts", "lib/billing/settlement.ts", "app/subscriptions"],
    note: "Exact chain verified against lib/funnel + app/subscriptions; not assumed.",
  },
  {
    name: "Auth / RBAC",
    steps: [
      "login (email/username+password)",
      "callback (exchange code → session)",
      "role resolution (app_users.role)",
      "route gating (requireRole)",
      "RLS (is_active_app_user/is_active_business_user/is_app_admin)",
    ],
    entry: ["app/auth/login/page.tsx", "app/auth/callback/route.ts"],
    evidence: ["lib/auth/require-role.ts", "lib/auth/roles.ts"],
  },
  {
    name: "Scheduled task generation",
    steps: [
      "Vercel cron (Sun 08:00)",
      "generate-tasks handler (CRON_SECRET bearer)",
      "deterministic due-date computation (task-generator.ts)",
      "task insert (idempotent by subscription+service+due_date)",
    ],
    entry: ["app/api/cron/generate-tasks/route.ts"],
    evidence: ["lib/server/generate-tasks-handler.ts", "lib/actions/task-generator.ts"],
  },
  {
    name: "Agent job lifecycle (GMK)",
    steps: [
      "authenticated admin request (Agent operator controls → auth.uid())",
      "bounded job enqueue (agent_jobs, required_capability)",
      "discovery (eligible jobs SELECT)",
      "claim_agent_job (lease)",
      "renew_agent_job_lease (long jobs)",
      "worker execution (tools + ollama)",
      "output validation (privacy/forbidden/secrets)",
      "complete_agent_job → awaiting_review / fail_agent_job",
      "review_agent_job (human, post-hoc)",
    ],
    entry: ["scripts/gmk-agent-worker/worker.mjs"],
    evidence: ["scripts/gmk-agent-worker/lib/claim-loop.mjs", "supabase/migrations/20260611120000_add_household_and_agent_foundations.sql"],
  },
];

// Module-level dependency edges (for change-impact analysis), not file-to-file noise.
export const DEPENDENCIES = [
  ["Auth / RBAC", "CRM / Leads"],
  ["Auth / RBAC", "Operator Inbox"],
  ["Auth / RBAC", "Billing / Invoicing"],
  ["Auth / RBAC", "GMK Agent Worker"],
  ["Auth / RBAC", "Agent operator controls"],
  ["Messaging ingestion", "Operator Inbox"],
  ["Messaging ingestion", "Notification / Email"],
  ["Operator Inbox", "Outbound messaging"],
  ["Outbound messaging", "Notification / Email"],
  ["CRM / Leads", "Funnel / Offers"],
  ["CRM / Leads", "Messaging ingestion"],
  ["Funnel / Offers", "Subscriptions"],
  ["Subscriptions", "Tasks / Workers"],
  ["Subscriptions", "Billing / Invoicing"],
  ["Clients", "Subscriptions"],
  ["Properties", "Subscriptions"],
  ["Services / Packages", "Subscriptions"],
  ["Billing / Invoicing", "Banking"],
  ["Billing / Invoicing", "Promotions"],
  ["Agent framework (DB substrate)", "GMK Agent Worker"],
  ["Agent framework (DB substrate)", "Agent operator controls"],
  ["GMK Agent Worker", "Agent operator controls"],
  ["Supabase infra", "Messaging ingestion"],
  ["Supabase infra", "Agent framework (DB substrate)"],
  ["Supabase infra", "Agent operator controls"],
  ["Supabase infra", "Auth / RBAC"],
  ["Supabase infra", "CRM / Leads"],
  ["Supabase infra", "Clients"],
  ["Supabase infra", "Properties"],
  ["Supabase infra", "Services / Packages"],
  ["Supabase infra", "Subscriptions"],
  ["Supabase infra", "Tasks / Workers"],
  ["Supabase infra", "Billing / Invoicing"],
  ["Supabase infra", "Banking"],
  ["Supabase infra", "Expenses"],
  ["Supabase infra", "Funnel / Offers"],
  ["Supabase infra", "Promotions"],
  ["Supabase infra", "Keys / Key logs"],
  ["Supabase infra", "Operator Inbox"],
  ["Supabase infra", "Notification / Email"],
  ["Supabase infra", "Vendors"],
  ["Vendors", "Expenses"],
];
