import type { LegalDocument } from "@/components/marketing/LegalPage";

const operatorSq = "STREHË Prona aktualisht operohet nga Milot Berisha në Prishtinë, Kosovë. Për pyetje ose kërkesa lidhur me të dhënat personale: info@streheprona.com · https://streheprona.com.";
const operatorEn = "STREHË Prona is currently operated by Milot Berisha in Prishtina, Kosovo. For questions or requests concerning personal data: info@streheprona.com · https://streheprona.com.";

export const privacyDocument: LegalDocument = {
  title: "Politika e Privatësisë / Privacy Policy",
  effectiveDate: "15 August 2026",
  albanian: [
    { title: "1. Kush jemi", paragraphs: [operatorSq] },
    { title: "2. Të dhënat që mbledhim", paragraphs: ["Kur na kontaktoni, mund të mbledhim emrin, email-in ose numrin e telefonit, shtetin e banimit, nëse jetoni jashtë Kosovës, zonën e apartamentit/shërbimit, mesazhin, mënyrën e preferuar të komunikimit dhe gjuhën. Mund të ruajmë të dhëna të fushatave, UTM dhe atribuimit të brendshëm.", "Nëse bëheni klient ose vazhdoni me konsultim dhe shërbim, mund të përpunojmë të dhëna kontakti, prone, konsultimesh, ofertash, abonimesh, evidenca shërbimi, fotografi ose dokumente, fatura dhe evidenca pagesash. Nuk mbledhim të dhëna të kartelave të pagesës përmes faqes."] },
    { title: "3. WhatsApp dhe shërbimet Meta", paragraphs: ["Meta mund t'i dërgojë STREHËS identifikues, kohë komunikimi, përmbajtje mesazhi/ngjarjeje dhe të dhëna teknike kur na kontaktoni përmes WhatsApp. STREHË përdor webhook vetëm për pranimin e ngjarjeve; ngjarjet e autentikuara mund të ruhen për qëllime operative dhe sigurie.", "STREHË nuk përdor të dhënat e webhook-ut për profilizim ose vendimmarrje të automatizuar dhe nuk i shkruan automatikisht në CRM ose të dhënat e klientëve."] },
    { title: "4. Si i përdorim të dhënat", paragraphs: ["Të dhënat përpunohen për t'iu përgjigjur kërkesave, organizuar konsultime e oferta, administruar marrëdhënie klientësh, shërbime, marrëveshje, fatura e pagesa, ruajtur evidenca, mbrojtur sigurinë dhe parandaluar keqpërdorimin."], bullets: ["hapa para kontratës ose zbatimi i marrëveshjes", "detyrime ligjore, interes legjitim operacional ose pëlqim kur kërkohet"] },
    { title: "5. Ofruesit dhe transferimet", paragraphs: ["Ofruesit aktualë përfshijnë Supabase (bazë të dhënash, autentikim, skedarë), Vercel (hostim), Resend (email transaksional) dhe Meta/WhatsApp për komunikime. Disa mund të operojnë ndërkombëtarisht; kur kërkohet, do të zbatohen masa mbrojtëse sipas ligjit në fuqi."] },
    { title: "6. Cookies, ruajtja dhe siguria", paragraphs: ["Faqja publike nuk përdor pixel-a reklamues, SDK analitike të palëve të treta ose cookies për profilizim. Portali i brendshëm përdor teknologji autentikimi për sesionet e stafit të autorizuar.", "Të dhënat ruhen për aq kohë sa është e arsyeshme për qëllimin, kërkesat kontraktuale, kontabël, ligjore, të sigurisë dhe kontestet. Jo të gjitha sistemet kanë afate automatike; fshirja mund të administrohet manualisht. Përdorim masa teknike dhe organizative, por asnjë sistem nuk është plotësisht i sigurt."] },
    { title: "7. Të drejtat, mosshitja dhe ndryshimet", paragraphs: ["Në varësi të ligjit, mund të kërkoni qasje, korrigjim, fshirje, kufizim, kundërshtim, bartje ose tërheqje pëlqimi në info@streheprona.com. Mund të kërkojmë verifikim identiteti; mund të keni të drejtë ankese te autoriteti kompetent në Kosovë.", "STREHË nuk i shet të dhënat personale dhe nuk përdor profilizim ose vendimmarrje të automatizuar. Kjo politikë mund të përditësohet; versioni aktual publikohet këtu."] },
  ],
  english: [
    { title: "1. Who we are", paragraphs: [operatorEn] },
    { title: "2. Information we collect", paragraphs: ["When you contact us, we may collect your name, email address or phone number, country of residence, whether you live abroad, apartment/service area, message, preferred communication method and language. We may record campaign, UTM and similar first-party attribution information.", "If you become a customer or proceed through consultation and onboarding, we may process contact, property, consultation, offer, subscription, service, photograph/document, invoice and payment-record information. We do not collect card-payment details through the website."] },
    { title: "3. WhatsApp and other Meta services", paragraphs: ["Meta may provide information associated with a WhatsApp communication, including identifiers, timestamps, message or event content and technical metadata. STREHË operates receive-only Meta webhooks; authenticated events may be stored for operational and security purposes.", "We do not use Meta webhook information for automated profiling or automated decision-making, and do not automatically write it to customer or CRM records."] },
    { title: "4. How we use information", paragraphs: ["We process information to respond to inquiries, arrange consultations and offers, administer customer and service relationships, contracts, invoices and payments, maintain records and system security, prevent abuse, and understand first-party attribution."], bullets: ["steps requested before a contract or performance of a contract", "legal obligations, legitimate operational interests, or consent where required"] },
    { title: "5. Service providers and transfers", paragraphs: ["Current providers include Supabase (database, authentication and storage), Vercel (hosting), Resend (transactional email), and Meta services including WhatsApp. Some providers operate internationally; where required, STREHË will apply appropriate safeguards under applicable law."] },
    { title: "6. Cookies, retention and security", paragraphs: ["The public website does not use advertising pixels, third-party analytics SDKs or behavioural-profiling cookies. The internal portal uses authentication technology for authorised staff sessions.", "Information is retained as reasonably necessary for its purpose and contractual, accounting, legal, security and dispute-resolution requirements. Not all systems use automatic expiry; deletion may be administered manually. We use technical and organisational safeguards, but no system can be completely secure."] },
    { title: "7. Your rights, no sale and changes", paragraphs: ["Subject to applicable law, you may request access, correction, deletion, restriction, objection, portability or withdrawal of consent at info@streheprona.com. We may request identity-verification information. You may also have a right to complain to the competent Kosovo authority.", "STREHË does not sell personal information and does not use it for automated profiling or decision-making. We may update this Policy; the current version is published here."] },
  ],
};

export const termsDocument: LegalDocument = {
  title: "Kushtet e Përdorimit / Terms of Use",
  effectiveDate: "15 August 2026",
  albanian: [
    { title: "1. Operatori", paragraphs: ["Kjo faqe dhe kanalet e komunikimit të STREHË operohen nga Milot Berisha, duke operuar STREHË Prona, Prishtinë, Kosovë · info@streheprona.com."] },
    { title: "2. Qëllimi i faqes", paragraphs: ["Faqja ofron informacion për kujdesin e apartamenteve dhe u mundëson klientëve potencialë të kontaktojnë STREHË, të kërkojnë informacion dhe të fillojnë konsultim. Kërkesa, mesazhi ose oferta nuk aktivizon vetvetiu shërbimin; aktivizimi, pagesat, ruajtja e çelësave dhe obligimet kërkojnë procesin dhe marrëveshjen përkatëse."] },
    { title: "3. Informacioni dhe përdorimi i pranueshëm", paragraphs: ["Ju pajtoheni të jepni informacion të saktë dhe të mos imitoni persona të tjerë ose të paraqisni qëllimisht informacion të rremë, të paligjshëm ose mashtrues."], bullets: ["mos ndërhyni në funksionim ose siguri dhe mos kërkoni qasje të paautorizuar", "mos dërgoni kod keqdashës ose keqpërdorim të automatizuar", "mos cenoni të drejtat e të tjerëve ose mos përdorni kanalet për qëllim të paligjshëm"] },
    { title: "4. Palët e treta, disponueshmëria dhe privatësia", paragraphs: ["WhatsApp dhe shërbimet e tjera të Meta mund t'u nënshtrohen kushteve dhe praktikave të tyre. Mund të ketë ndërprerje, gabime ose ndryshime. Informacioni në faqe është i përgjithshëm dhe nuk zëvendëson marrëveshjen e shërbimit. Të dhënat personale trajtohen sipas Politikës së Privatësisë: https://streheprona.com/privacy."] },
    { title: "5. Pronësia, përgjegjësia dhe ndryshimet", paragraphs: ["Emri STREHË, identiteti vizual, përmbajtja dhe materialet origjinale nuk mund të riprodhohen ose përdoren komercialisht pa leje, përveçse kur lejohet nga ligji. Asgjë nuk kufizon të drejta që nuk mund të kufizohen ligjërisht. Detyrimet e veçanta të shërbimit rregullohen nga marrëveshja përkatëse. Këto Kushte mund të përditësohen; pyetjet dërgohen në info@streheprona.com."] },
  ],
  english: [
    { title: "1. Operator", paragraphs: ["This website and STREHË communication channels are operated by Milot Berisha, operating STREHË Prona, Prishtina, Kosovo · info@streheprona.com."] },
    { title: "2. Purpose of the website", paragraphs: ["The website provides apartment-care information and lets prospective customers contact us, request information and begin a consultation. An inquiry, WhatsApp/social-media message, information or offer does not itself activate a service; activation, payment, key custody and obligations are subject to the applicable process and separate agreement where required."] },
    { title: "3. Information and acceptable use", paragraphs: ["You agree to provide accurate information and not impersonate another person or intentionally submit false, unlawful or misleading information."], bullets: ["do not interfere with operation or security, or attempt unauthorised access", "do not submit malicious code or automated abuse", "do not infringe another person's rights or use services unlawfully"] },
    { title: "4. Third parties, availability and privacy", paragraphs: ["WhatsApp and other Meta services are subject to their own terms and privacy practices. Interruptions, errors or changes may occur. Website information is general and does not replace a separately executed service agreement. Personal information is handled under https://streheprona.com/privacy."] },
    { title: "5. Intellectual property, responsibility and changes", paragraphs: ["The STREHË name, branding, content, layout and original materials may not be reproduced or used commercially without permission except as permitted by law. Nothing limits rights that cannot lawfully be excluded. Specific service obligations are governed by the applicable agreement. These Terms may be updated; questions may be sent to info@streheprona.com."] },
  ],
};

export const deletionDocument: LegalDocument = {
  title: "Fshirja e të Dhënave / Data Deletion Instructions",
  effectiveDate: "15 August 2026",
  albanian: [
    { title: "Kërkesa për fshirje", paragraphs: ["Mund të kërkoni fshirjen e të dhënave personale që kontrollohen nga STREHË, përfshirë të dhënat e marra përmes faqes ose, kur zbatohet, WhatsApp apo shërbimeve Meta. Dërgoni email në info@streheprona.com me subjektin: Kërkesë për Fshirjen e të Dhënave."], bullets: ["emrin", "email-in ose numrin e telefonit të përdorur", "kanalin e komunikimit dhe datën e përafërt, nëse dihet"] },
    { title: "Verifikimi dhe hapat e mëtejshëm", paragraphs: ["Mos dërgoni fjalëkalime, access token ose sekrete të tjera. Për të parandaluar fshirjen e paautorizuar, mund të kërkojmë verifikim të arsyeshëm të identitetit. Do të identifikojmë të dhënat e lidhura me ju dhe, kur kërkohet nga ligji, të dhënat e pranueshme do të fshihen ose bëhen jo-personalisht të identifikueshme.", "Disa të dhëna mund të ruhen për detyrime ligjore, kontraktuale, kontabël, sigurie, parandalim mashtrimi, konteste ose kërkesa ligjore. Kërkesat trajtohen pa vonesa të panevojshme brenda afateve ligjore."] },
    { title: "Meta dhe WhatsApp", paragraphs: ["Për të dhëna të marra përmes WhatsApp, Facebook, Messenger ose Instagram, tregoni shërbimin përkatës. Kjo faqe vlen për të dhënat e kontrolluara nga STREHË; fshirja nga sistemet tona nuk fshin domosdoshmërisht të dhëna që Meta ose palë të tjera i kontrollojnë në mënyrë të pavarur. Pyetje: info@streheprona.com. Shihni edhe https://streheprona.com/privacy."] },
  ],
  english: [
    { title: "Making a deletion request", paragraphs: ["You may request deletion of personal information controlled by STREHË, including website information and, where applicable, WhatsApp or connected Meta-service information. Email info@streheprona.com with the subject: Data Deletion Request."], bullets: ["your name", "the email address or phone number used to contact STREHË", "the communication channel and approximate interaction date, if known"] },
    { title: "Verification and next steps", paragraphs: ["Do not send passwords, access tokens or other authentication secrets. To protect against unauthorised deletion, we may request reasonable identity-verification information. We will identify controlled information associated with you and, where required by law, delete eligible data or make it no longer personally identifiable.", "Some information may be retained for legal, contractual, accounting, security, fraud-prevention, dispute-resolution or legal-claim purposes. Requests are handled without undue delay within applicable legal periods."] },
    { title: "Meta and WhatsApp information", paragraphs: ["For information received through WhatsApp, Facebook, Messenger or Instagram, identify the relevant service. This page concerns information controlled by STREHË; deletion from our systems does not necessarily delete information independently controlled by Meta or another provider. Questions: info@streheprona.com. See https://streheprona.com/privacy."] },
  ],
};
