"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import AddressFields from "../components/AddressFields";

type Municipality = {
  id: string;
  name: string;
};

type Location = {
  id: string;
  name: string;
  type: "neighborhood" | "village" | "other";
  municipality_id: string;
};

type Client = {
  id: string;
  full_name: string | null;
  company_name: string | null;
};

type PropertyFormProps = {
  municipalities: Municipality[];
  locations: Location[];
  clients: Client[];
  createProperty: (formData: FormData) => void;
};

export default function PropertyForm({
  municipalities,
  locations,
  clients,
  createProperty,
}: PropertyFormProps) {
  const [selectedMunicipalityId, setSelectedMunicipalityId] = useState("");
  const searchParams = useSearchParams();

  const preselectedOwnerId = useMemo(() => {
    return searchParams.get("owner_client_id") || "";
  }, [searchParams]);

  return (
    <form action={createProperty} className="space-y-6">
      <div className="grid-2">
        <div className="field">
          <label htmlFor="property_code">Property Code</label>
          <input
            id="property_code"
            className="input"
            value="Auto-generated by system"
            disabled
          />
        </div>

        <div className="field">
          <label htmlFor="title">Title</label>
          <input
            id="title"
            name="title"
            className="input"
            placeholder="Apartment - City Center"
            required
          />
        </div>
      </div>

      <div className="field">
        <label htmlFor="owner_client_id">Owner</label>
        <select
          id="owner_client_id"
          name="owner_client_id"
          className="input"
          required
          defaultValue={preselectedOwnerId}
        >
          <option value="" disabled>
            Select owner
          </option>

          {clients.map((client) => {
            const label = client.company_name || client.full_name || client.id;

            return (
              <option key={client.id} value={client.id}>
                {label}
              </option>
            );
          })}
        </select>
      </div>

      <AddressFields
        municipalities={municipalities}
        locations={locations}
        selectedMunicipalityId={selectedMunicipalityId}
        onMunicipalityChange={setSelectedMunicipalityId}
      />

      <div className="grid-2">
        <div className="field">
          <label htmlFor="property_type">Property Type</label>
          <select
            id="property_type"
            name="property_type"
            className="input"
            defaultValue=""
          >
            <option value="">Select type</option>
            <option value="apartment">Apartment</option>
            <option value="house">House</option>
            <option value="office">Office</option>
            <option value="shop">Shop</option>
            <option value="land">Land</option>
          </select>
        </div>

        <div className="field">
          <label htmlFor="status">Status</label>
          <select
            id="status"
            name="status"
            className="input"
            defaultValue="active"
          >
            <option value="active">Active</option>
            <option value="vacant">Vacant</option>
            <option value="inactive">Inactive</option>
            <option value="under_maintenance">Under Maintenance</option>
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <button type="submit" className="btn btn-primary">
          Save Property
        </button>

        <Link href="/properties" className="btn btn-ghost">
          Cancel
        </Link>
      </div>
    </form>
  );
}